baseURL = "https://hugity.github.io/j579phtppg1h7mckq2ajzfxawn7phhk0/"
defaultLanguage = "en"
title = "MDFriday"
description = "MDFriday homepage, showcase the product or service."
theme = "theme-long-teng"

[params]
    Author = 'sunwei'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'